/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversaRouteImport } from './routes/conversa'
import { Route as LicaoLicaoIdRouteImport } from './routes/licao.$licaoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversaRoute = ConversaRouteImport.update({
  id: '/conversa',
  path: '/conversa',
  getParentRoute: () => rootRouteImport,
} as any)
const LicaoLicaoIdRoute = LicaoLicaoIdRouteImport.update({
  id: '/licao/$licaoId',
  path: '/licao/$licaoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversa': typeof ConversaRoute
  '/licao/$licaoId': typeof LicaoLicaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversa': typeof ConversaRoute
  '/licao/$licaoId': typeof LicaoLicaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversa': typeof ConversaRoute
  '/licao/$licaoId': typeof LicaoLicaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conversa' | '/licao/$licaoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conversa' | '/licao/$licaoId'
  id: '__root__' | '/' | '/conversa' | '/licao/$licaoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversaRoute: typeof ConversaRoute
  LicaoLicaoIdRoute: typeof LicaoLicaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversa': {
      id: '/conversa'
      path: '/conversa'
      fullPath: '/conversa'
      preLoaderRoute: typeof ConversaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licao/$licaoId': {
      id: '/licao/$licaoId'
      path: '/licao/$licaoId'
      fullPath: '/licao/$licaoId'
      preLoaderRoute: typeof LicaoLicaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversaRoute: ConversaRoute,
  LicaoLicaoIdRoute: LicaoLicaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
